name: asdish
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.31.0
  go_router: ^14.1.1
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  intl_phone_field: ^3.2.0
  cart_stepper: ^4.3.0
  firebase_auth: ^4.19.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9


flutter:

  uses-material-design: true




